### ISSUE TITLE
Possible bug in step check

### ISSUE THREAD

**Issue by Lun4m** [intarga/olympian#42]
Shouldn't the order of the last two if conditions be reversed?
https://github.com/intarga/olympian/blob/74129f9497e38700d3879d4d1aa02c95a8b92646/src/qc_tests/step_check.rs#L28-L43

**Comment by intarga** [comment]
Yes good catch. I'll fix this in the current PR. I expect to catch some other similar bugs by writing test cases for all the checks in that PR
